#!/usr/bin/python
# Software License Agreement (BSD License)
#
# Copyright (c) 2008, I Heart Engineering
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of I Heart Engineering nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

import os
import sys
import gobject
import gtk
import appindicator
import subprocess
import rosgraph.masterapi

class TurtleBotIndicator:
    def __init__(self):
        self._ind = appindicator.Indicator ("turtlebot-indicator", "turtlebot-idle", appindicator.CATEGORY_APPLICATION_STATUS)
        self._ind.set_status (appindicator.STATUS_ACTIVE)
        self._exit = False
        self._menu = gtk.Menu()
        self._menu.set_double_buffered(True)
        self._master = rosgraph.masterapi.Master('/turtlebot-indicator')
        self._master_update = False
        self._master_online = False
        self._turtlebot_online = False
        self._topics = [] # List of Topics
        self._nodes = [] # List of Topics
        self._pubs = {} # Publishers keyed by topic
        self._subs = {} # Subscribers keyed by topic

    def update(self):
        p = subprocess.Popen(['turtlebot-network','interface'], stdout=subprocess.PIPE)
        output = p.communicate()[0].strip()
        p.wait()
        if output != "lo":
            self._network_online = True
        else:
            self._network_online = False

        if not self._master_online and self._master.is_online():
            self._master_update = True
            self._master_online = True
        elif self._master_online and not self._master.is_online():
            self._master_update = True
            self._master_online = False
            self._turtlebot_online = False
            self._topics = []
            self._nodes = []
            self._pubs = {}
            self._subs = {}
        else:
            self._master_update = False
        self.update_topic_info()
        self.update_node_info()
        self.build_menu()

    def update_topic_info(self):
        if self._master.is_online():
            topic_pubs, topic_subs, srvs = self._master.getSystemState()
            for topic,pubs in topic_pubs:
                self._pubs[topic] = pubs
            for topic,subs in topic_subs:
                self._subs[topic] = subs
            self._topics = list(set(self._pubs.keys() + self._subs.keys()))
            self._topics.sort()
        else:
            self._topics = []
            self._pubs = {}
            self._subs = {}

    def update_node_info(self):
        # This might be wrong because a node may not be puslishing
        # or subscribing, but this is how rosnode does it.
        # If a node never publishes or subscribes, is it really a node?
        if self._master.is_online() and self._topics != None and self._topics != []:
            self._nodes=[]
            for nodes in self._pubs.values():
                self._nodes = self._nodes + nodes
            for nodes in self._subs.values():
                self._nodes = self._nodes + nodes
            self._nodes = list(set(self._nodes))
            self._turtlebot_online = False
            for node in self._nodes:
              if node == "/turtlebot_node":
                  self._turtlebot_online = True
            #self._nodes = list(set(self._pubs.values() + self._subs.values()))

    def menuitem_shutdown (self,item):
        os.system('gksudo "initctl stop turtlebot"')

    def menuitem_startup (self,item):
        os.system('gksudo "initctl start turtlebot"')

    def build_menu(self):
        self._menu = gtk.Menu()

        if self._network_online:
            if self._turtlebot_online:
                self._ind.set_icon ("turtlebot-panel")
                topic_item = gtk.MenuItem("Stop TurtleBot")
                topic_item.set_sensitive(True)
                topic_item.show()
                topic_item.connect("activate",self.menuitem_shutdown)
                self._menu.append(topic_item)
            else:
                self._ind.set_icon ("turtlebot-idle")
                topic_item = gtk.MenuItem("Start TurtleBot")
                topic_item.set_sensitive(True)
                topic_item.show()
                topic_item.connect("activate",self.menuitem_startup)
                self._menu.append(topic_item)
        else:
            self._ind.set_icon ("turtlebot-idle")
            disconnect_item = gtk.MenuItem("disconnected")
            disconnect_item.set_sensitive(False)
            disconnect_item.show()
            self._menu.append(disconnect_item)
        self._ind.set_menu(self._menu)

    def run(self):
        self.update()
        if not self._exit:
            source_id = gobject.timeout_add(2000, self.run)

    def start(self):
        self.run()
        try:
            gtk.main()
        except KeyboardInterrupt:
            self.stop()
            sys.exit(os.EX_OK)

    def stop(self):
        self._exit = True

if __name__ == "__main__":
    tbi = TurtleBotIndicator()
    tbi.start()
